# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tmp_LogIn.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1440, 900)
        self.horizontalLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 100, 691, 566))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stopbtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stopbtn.sizePolicy().hasHeightForWidth())
        self.stopbtn.setSizePolicy(sizePolicy)
        self.stopbtn.setMinimumSize(QtCore.QSize(0, 30))
        self.stopbtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stopbtn.setObjectName("stopbtn")
        self.verticalLayout_2.addWidget(self.stopbtn)
        self.changebtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changebtn.sizePolicy().hasHeightForWidth())
        self.changebtn.setSizePolicy(sizePolicy)
        self.changebtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.changebtn.setObjectName("changebtn")
        self.verticalLayout_2.addWidget(self.changebtn)
        self.logoutbtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoutbtn.sizePolicy().hasHeightForWidth())
        self.logoutbtn.setSizePolicy(sizePolicy)
        self.logoutbtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.logoutbtn.setObjectName("logoutbtn")
        self.verticalLayout_2.addWidget(self.logoutbtn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(self.horizontalLayoutWidget)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 189, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-10, -10, 201, 814))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.GroupBox_4 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.GroupBox_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox_4.sizePolicy().hasHeightForWidth())
        self.GroupBox_4.setSizePolicy(sizePolicy)
        self.GroupBox_4.setMinimumSize(QtCore.QSize(0, 120))
        self.GroupBox_4.setMaximumSize(QtCore.QSize(16777215, 120))
        self.GroupBox_4.setTitle("")
        self.GroupBox_4.setObjectName("GroupBox_4")
        self.person_4 = QtWidgets.QPushButton(self.GroupBox_4)
        self.person_4.setGeometry(QtCore.QRect(-10, 10, 201, 100))
        self.person_4.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.person_4.setFont(font)
        self.person_4.setText("")
        self.person_4.setObjectName("person_4")
        self.msgcnt_4 = QtWidgets.QLabel(self.GroupBox_4)
        self.msgcnt_4.setGeometry(QtCore.QRect(120, 50, 60, 16))
        self.msgcnt_4.setText("")
        self.msgcnt_4.setAlignment(QtCore.Qt.AlignCenter)
        self.msgcnt_4.setObjectName("msgcnt_4")
        self.verticalLayout.addWidget(self.GroupBox_4)
        self.GroupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.GroupBox_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox_2.sizePolicy().hasHeightForWidth())
        self.GroupBox_2.setSizePolicy(sizePolicy)
        self.GroupBox_2.setMinimumSize(QtCore.QSize(0, 120))
        self.GroupBox_2.setMaximumSize(QtCore.QSize(16777215, 120))
        self.GroupBox_2.setTitle("")
        self.GroupBox_2.setObjectName("GroupBox_2")
        self.person_2 = QtWidgets.QPushButton(self.GroupBox_2)
        self.person_2.setGeometry(QtCore.QRect(-10, 10, 201, 100))
        self.person_2.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.person_2.setFont(font)
        self.person_2.setText("")
        self.person_2.setObjectName("person_2")
        self.msgcnt_2 = QtWidgets.QLabel(self.GroupBox_2)
        self.msgcnt_2.setGeometry(QtCore.QRect(120, 50, 60, 16))
        self.msgcnt_2.setText("")
        self.msgcnt_2.setAlignment(QtCore.Qt.AlignCenter)
        self.msgcnt_2.setObjectName("msgcnt_2")
        self.verticalLayout.addWidget(self.GroupBox_2)
        self.GroupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.GroupBox_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox_3.sizePolicy().hasHeightForWidth())
        self.GroupBox_3.setSizePolicy(sizePolicy)
        self.GroupBox_3.setMinimumSize(QtCore.QSize(0, 120))
        self.GroupBox_3.setMaximumSize(QtCore.QSize(16777215, 120))
        self.GroupBox_3.setTitle("")
        self.GroupBox_3.setObjectName("GroupBox_3")
        self.person_3 = QtWidgets.QPushButton(self.GroupBox_3)
        self.person_3.setGeometry(QtCore.QRect(-10, 10, 201, 100))
        self.person_3.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.person_3.setFont(font)
        self.person_3.setText("")
        self.person_3.setObjectName("person_3")
        self.msgcnt_3 = QtWidgets.QLabel(self.GroupBox_3)
        self.msgcnt_3.setGeometry(QtCore.QRect(120, 50, 60, 16))
        self.msgcnt_3.setText("")
        self.msgcnt_3.setAlignment(QtCore.Qt.AlignCenter)
        self.msgcnt_3.setObjectName("msgcnt_3")
        self.verticalLayout.addWidget(self.GroupBox_3)
        self.GroupBox_1 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.GroupBox_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox_1.sizePolicy().hasHeightForWidth())
        self.GroupBox_1.setSizePolicy(sizePolicy)
        self.GroupBox_1.setMinimumSize(QtCore.QSize(0, 120))
        self.GroupBox_1.setMaximumSize(QtCore.QSize(16777215, 120))
        self.GroupBox_1.setTitle("")
        self.GroupBox_1.setObjectName("GroupBox_1")
        self.person_1 = QtWidgets.QPushButton(self.GroupBox_1)
        self.person_1.setGeometry(QtCore.QRect(-10, 10, 201, 100))
        self.person_1.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.person_1.setFont(font)
        self.person_1.setText("")
        self.person_1.setObjectName("person_1")
        self.msgcnt_1 = QtWidgets.QLabel(self.GroupBox_1)
        self.msgcnt_1.setGeometry(QtCore.QRect(120, 50, 60, 16))
        self.msgcnt_1.setText("")
        self.msgcnt_1.setAlignment(QtCore.Qt.AlignCenter)
        self.msgcnt_1.setObjectName("msgcnt_1")
        self.verticalLayout.addWidget(self.GroupBox_1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.history = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.history.setMinimumSize(QtCore.QSize(350, 100))
        self.history.setMaximumSize(QtCore.QSize(500, 1000))
        self.history.setReadOnly(True)
        self.history.setObjectName("history")
        self.verticalLayout_3.addWidget(self.history)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 100))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.lineEdit.setMaxLength(4096)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fileInput = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.fileInput.setMinimumSize(QtCore.QSize(70, 70))
        self.fileInput.setMaximumSize(QtCore.QSize(70, 70))
        self.fileInput.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fileInput.setObjectName("fileInput")
        self.verticalLayout_4.addWidget(self.fileInput)
        self.textInput = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.textInput.setMinimumSize(QtCore.QSize(70, 70))
        self.textInput.setMaximumSize(QtCore.QSize(70, 70))
        self.textInput.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.textInput.setObjectName("textInput")
        self.verticalLayout_4.addWidget(self.textInput)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.stopbtn.setText(_translate("MainWindow", "stop"))
        self.changebtn.setText(_translate("MainWindow", "聊天訊息"))
        self.logoutbtn.setText(_translate("MainWindow", "登出"))
        self.fileInput.setText(_translate("MainWindow", "檔案"))
        self.textInput.setText(_translate("MainWindow", "傳送"))
