# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tmp_app.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1440, 900)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(567, 230, 331, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(34)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.account_layout = QtWidgets.QHBoxLayout()
        self.account_layout.setObjectName("account_layout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.account_layout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        self.lineEdit.setFont(font)
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhLatinOnly)
        self.lineEdit.setMaxLength(20)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.account_layout.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.account_layout)
        self.password_layout = QtWidgets.QHBoxLayout()
        self.password_layout.setObjectName("password_layout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.password_layout.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhLatinOnly)
        self.lineEdit_2.setMaxLength(30)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.password_layout.addWidget(self.lineEdit_2)
        self.verticalLayout_3.addLayout(self.password_layout)
        self.instr_layout = QtWidgets.QHBoxLayout()
        self.instr_layout.setObjectName("instr_layout")
        self.signIn_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(".Geeza Pro PUA")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.signIn_button.setFont(font)
        self.signIn_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signIn_button.setObjectName("signIn_button")
        self.instr_layout.addWidget(self.signIn_button)
        self.signUp_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(".Geeza Pro PUA")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.signUp_button.setFont(font)
        self.signUp_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signUp_button.setObjectName("signUp_button")
        self.instr_layout.addWidget(self.signUp_button)
        self.verticalLayout_3.addLayout(self.instr_layout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "德田 B.O.T."))
        self.label_2.setText(_translate("Form", "帳號："))
        self.label_3.setText(_translate("Form", "密碼："))
        self.signIn_button.setText(_translate("Form", "Sign In"))
        self.signUp_button.setText(_translate("Form", "Sign Up"))
